### ISSUE TITLE
array_multisort does not sort

### ISSUE THREAD

**Issue by dmecke** [thecodingmachine/safe#104]
Given the following phpunit test case:

```
$integers = [3, 1, 2];

$sort = [];
foreach ($integers as $k => $value) {
    $sort[$k][] = $value;
}
array_multisort($sort, SORT_ASC, $integers);

Assert::assertSame(1, $integers[0]);
Assert::assertSame(2, $integers[1]);
Assert::assertSame(3, $integers[2]);
```

it passes with php's native `array_mulitsort`. Using `Safe\array_multisort` it fails, though. The array `$integers` is left unchanged. In the documentation (and therefore in safe) the third parameter is _not_ a reference while php actually treats it as one.

**Comment by moufmouf** [comment]
Hey @dmecke !

I just wrote a unit test to try to reproduce your problem, but I fail reproducing it.

The code you give seems to work OK with Safe and without Safe. Are you sure there is an issue? Could it be dependent on the PHP version (I'm testing with PHP 7.2)

**Comment by dmecke** [comment]
Hm, yes, I just reproced it on my machine with php 7.2. I'd like to open a pull request, but I am not sure where this test should go. Is the `generator/tests` directory the right place? And if so, where should a function specific test like this go?

**Comment by dmecke** [comment]
I've created a pull request. I think travis fails because of this (so the reproduction works), but I am not sure if the error below is related to a misconfiguration on my side.

**Comment by Kharhamel** [comment]
this function was removed in #167

**Comment by Kharhamel** [comment]
This functiun was removed in the v1.0.0 release
