### ISSUE TITLE
fsockopen() throws \ErrorException

### ISSUE THREAD

**Issue by ke20** [thecodingmachine/safe#107]
In a Symfony project I have a method with the code as below : 

```php
<?php

use Safe\Exceptions\FilesystemException;
use Safe\Exceptions\NetworkException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use function Safe\fclose;
use function Safe\fsockopen;

class myClass
{
    public function myMethod()
    {
        try {
            $fp = fsockopen($connectionString);
            fclose($fp);
        } catch (NetworkException | FilesystemException $e) {
            throw new HttpException(Response::HTTP_SERVICE_UNAVAILABLE, 'socket connection has failed');
        }
    }
}
```

When the calls to the function `fsockopen()` failed, it's an \ErrorException which is throwed and not a `Safe\Exceptions\NetworkException`.

In the [php doc](https://www.php.net/manual/en/function.fsockopen.php#refsect1-function.fsockopen-errors) we can see :
```
Throws E_WARNING if hostname is not a valid domain.
```
It's an expected behavior or it's bug ?

Should I catch the `\ErrorException` in addition to `NetworkException | FilesystemException` ?

Good lib ;)

**Comment by B-Galati** [comment]
It can be closed, we figured out that it was PhpUnit error handler that was catching the error before it can be thrown by Safe.

If it can help, we created a function to execute code without any error handler:

```
final protected function executeWithoutErrorHandler(callable $function): void
    {
        set_error_handler(function () {});

        try {
            $function();
        } finally {
            restore_error_handler();
        }
    }
```

**Comment by moufmouf** [comment]
:+1: Indeed, Safe does not catch "warnings" sent by the PHP functions. Most PHP functions will throw warnings and therefore, a error handler like PHPUnit or Symfony's will probably trigger an error before Safe can.

I've been wondering whether I should silence the warnings or not (I could do that in the Safe functions using "@fsockopen". So far, I've resisted the urge to do so. Let me know if you think I should.

**Comment by B-Galati** [comment]
IMHO it's more reliable with the current behavior but not the best in terms of DX.

In any case, it would be a good idea to document it if not done yet.
