### ISSUE TITLE
List of safe functions

### ISSUE THREAD

**Issue by goldingdamien** [thecodingmachine/safe#108]
Is there a list of safe functions that can be used?

**Comment by moufmouf** [comment]
Absolutely! It is available here: https://github.com/thecodingmachine/safe/blob/master/generated/functionsList.php

You can use it in your own programs, this file will not move in the coming versions. I'm already relying on it for some external plugins like the [Safe PHPStan rules](https://github.com/thecodingmachine/phpstan-safe-rule/)
