### ISSUE TITLE
 Class "Rector\Rector\Function_\FunctionReplaceRector" was not found

### ISSUE THREAD

**Issue by Aerendir** [thecodingmachine/safe#109]
Trying to use Rector, I get this errors:

> PHP Fatal error:  Uncaught Rector\Exception\DependencyInjection\ClassNotFoundException: Class "Rector\Rector\Function_\FunctionReplaceRector" was not found while loading "vendor/thecodingmachine/safe/rector-migrate.yml" file. Are you sure it is correctly spelled?

I've configured Rector to import the config file, but also using it directly from the command line I get the same error.

Looking in the code of Rector, I cannot find any namespace `Rector\Rector\Function_\`, so is obvious the class doesn't exist.

I've never used Rector nor this library, so I'm not able to fix the issue on my own at this time.

Anyone who can understand what is going on?

I'm using Rector 0.4.10, so I think the config file provided by this library is suited for the version ^0.3.

Any ideas?

**Comment by moufmouf** [comment]
This is definitely related to the rector version. The rector file provided by Safe is designed to run against Rector 0.3.
I'll be working on a new rector file for 0.4.
