### ISSUE TITLE
Add support for strrpos

### ISSUE THREAD

**Issue by j6s** [thecodingmachine/safe#117]
The `strrpos` method returns `false` if the needle is not found:

https://www.php.net/manual/en/function.strrpos.php

Not sure if we can even detect this wording because the docs themselves are pretty shy about mentioning this.

**Comment by moufmouf** [comment]
Hey @j6s,

Actually, Safe returns `false` only for error cases, not for any method that could return false.
In the case of "strrpos" (or 'strpos'), we can advocate that "false" is a legitimate return type. It means "I did not find the string" and not: something went wrong when I was analyzing the string.

See also: https://github.com/thecodingmachine/safe/issues/78

**Comment by j6s** [comment]
You are right, this is not an error case.
Sorry for the confusion.
