### ISSUE TITLE
getimagesize() is not present in the list

### ISSUE THREAD

**Issue by Aerendir** [thecodingmachine/safe#118]
The function `getimagesize()` returns the image size and other info about it or false on failure, but it is not present in the library.

[Documentation on PHP.net](https://www.php.net/manual/en/function.getimagesize.php#refsect1-function.getimagesize-returnvalues)

> Returns an array with up to 7 elements. Not all image types will include the channels and bits elements.
> ...
> On failure, FALSE is returned.

**Comment by moufmouf** [comment]
Closed by #123
