### ISSUE TITLE
array_flip missing

### ISSUE THREAD

**Issue by simPod** [thecodingmachine/safe#119]
Hi, shouldn't there be `array_flip()` in this lib?

> * @return array|null Returns the flipped array on success and NULL on failure.

Thanks!

**Comment by Kharhamel** [comment]
Thanks! Indeed, there are methods that return null instead of false on failure.
I started a PR to detect those:

https://github.com/thecodingmachine/safe/pull/122

**Comment by Kharhamel** [comment]
merged
