### ISSUE TITLE
Add image creation methods

### ISSUE THREAD

**Issue by WillyReyno** [thecodingmachine/safe#125]
Image creation php functions all return false when an error occur, I think they should have their own Safe counterparts! 

- https://www.php.net/manual/fr/function.imagecreate.php
- https://www.php.net/manual/fr/function.imagecreatefrombmp.php
- https://www.php.net/manual/fr/function.imagecreatefromgd2.php
- https://www.php.net/manual/fr/function.imagecreatefromgd2part.php
- https://www.php.net/manual/fr/function.imagecreatefromgd.php
- https://www.php.net/manual/fr/function.imagecreatefromgif.php
- https://www.php.net/manual/fr/function.imagecreatefromjpeg.php
- https://www.php.net/manual/fr/function.imagecreatefrompng.php
- https://www.php.net/manual/fr/function.imagecreatefromstring.php
- https://www.php.net/manual/fr/function.imagecreatefromwbmp.php
- https://www.php.net/manual/fr/function.imagecreatefromwebp.php
- https://www.php.net/manual/fr/function.imagecreatefromxbm.php
- https://www.php.net/manual/fr/function.imagecreatefromxpm.php
- https://www.php.net/manual/fr/function.imagecreatetruecolor.php

**Comment by Kharhamel** [comment]
#132

**Comment by moufmouf** [comment]
Thanks @Kharhamel for adding those!
