### ISSUE TITLE
Add .gitattributes

### ISSUE THREAD

**Issue by reedy** [thecodingmachine/safe#126]
Hello!

Is it possible to get a .gitattributes file added to this repo?

See https://medium.com/@pablorsk/be-a-git-ninja-the-gitattributes-file-e58c07c9e915 and https://madewithlove.be/gitattributes/ for more information

Thanks!

**Comment by moufmouf** [comment]
Hey @reedy,

Sure, it makes a lot of sense. I've never played with .gitattributes before. If you are used to it, do you want to contribute a PR?

**Comment by reedy** [comment]
Yeah, I'm happy to do so. Will try and get it sorted later today :)

**Comment by reedy** [comment]
Ok, PR for the root/dotfile type files up

What about the other directories? Is `performance` just a performance benchmark?

I'm presuming `generator` isn't needed by 3rd party inclusions, but obviously `generated` and `lib` are? (because they're included in composer.json)

**Comment by moufmouf** [comment]
Yes "performance" is only for a performance benchmark.
And "generator" is used to generate "generated" files and is not needed at runtime.

So you can blacklist both directories.

**Comment by reedy** [comment]
Extra directories added

**Comment by moufmouf** [comment]
Thanks a lot!
