### ISSUE TITLE
apcu_delete @return type is wrong

### ISSUE THREAD

**Issue by walkonthemarz** [thecodingmachine/safe#135]
https://github.com/thecodingmachine/safe/blob/4e8f840f0a0a2ea167813c3994a7fc527c3c2182/generated/apcu.php#L78

**Comment by Kharhamel** [comment]
Can you elaborate? The php doc states:
"If key is an array, an indexed array of the keys is returned. Otherwise TRUE is returned on success, or FALSE on failure".
"@return bool|array" looks correct

**Comment by Kharhamel** [comment]
nevermind, I didn't notice our generated apcu_delete return typehint was 'void'. It should be fixed by #145

**Comment by moufmouf** [comment]
apcu_delete should clearly be removed as trying to delete a non existant cache key is not really an error (the key can be removed by APCu on its own).
Related: #136 

TODO: we should remove this function from the next major Safe release.

**Comment by Kharhamel** [comment]
#150

**Comment by Kharhamel** [comment]
removed in 1.0.0-beta2
