### ISSUE TITLE
Missing array_replace_recursive and array_replace

### ISSUE THREAD

**Issue by boesing** [thecodingmachine/safe#143]
Hey guys,

I recently started using this library and realized that at least some `array_` functions are missing.

- `array_replace_recursive`
- `array_replace`

I tried to find how the package searches for functions to generate. However, I did not dive that deep into the generator code to find why those functions are missing. But as they are not listed in the ignored functions file, I think its worth to probably dig a bit deeper into the code to find the solution.

Thanks in advance.

**Comment by Kharhamel** [comment]
We use regexp to parse the php documentation to detect which functions to edit. Since the doc correctly states 'return null on error', I guess it uses a specific formulation which doesn't pass any regexp. I will try to do it this week, unless you want to do it yourself?

**Comment by Kharhamel** [comment]
#145

**Comment by Kharhamel** [comment]
this was added in the v1.0.0 release
