### ISSUE TITLE
Implement psr2 and generated functions

### ISSUE THREAD

**Issue by vladyslavstartsev** [thecodingmachine/safe#15]
As you can see here. The comperation is with `FALSE` and not `false`.

If you look in the [psr2](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull), you will see that it's wrong.

https://github.com/thecodingmachine/safe/blob/a9415e4b4b71687d2200e1a5d98bc3933a0cc8ec/generated/eio.php#L24

Is that ok to have `FALSE`?

**Comment by moufmouf** [comment]
You are 100% right.

I should certainly call a CS fixer on generated files automatically.

**Comment by moufmouf** [comment]
Fixed in #19 !
Thanks for reporting.
