### ISSUE TITLE
Incorrect createFromPhpError() method?

### ISSUE THREAD

**Issue by snapshotpl** [thecodingmachine/safe#169]
Every generated exception method e.g. https://github.com/thecodingmachine/safe/blob/master/generated/Exceptions/FilesystemException.php contains createFromPhpError() method where exception is created from `json_last_error()`. Is it correct behaviour?

Source: https://github.com/thecodingmachine/safe/blob/50f1e6021c133510282d6f61be259c2cd0f0dbd4/generator/src/FileCreator.php#L157

**Comment by Kharhamel** [comment]
No it's not. Looks like I was dumb enough to copy paste the wrong code. I will fix this soon

**Comment by Kharhamel** [comment]
Also we should have some kind of tests for theses exceptions generated exceptions

**Comment by Kharhamel** [comment]
#170

**Comment by Kharhamel** [comment]
this is in the beta4. however i think we feel like there is something to improve with the way we generate our exceptions.

**Comment by snapshotpl** [comment]
@Kharhamel you talk about duplication?
