### ISSUE TITLE
drop json.php

### ISSUE THREAD

**Issue by vladyslavstartsev** [thecodingmachine/safe#18]
drop [json.php](https://github.com/thecodingmachine/safe/blob/master/generated/json.php) when php 7.3 is out. It now [throws errors by default](https://laravel-news.com/php-7-3-json-error-handling)

**Comment by moufmouf** [comment]
PHP 7.3 adds a new flag `JSON_THROW_ON_ERROR` but you must explicitly set it.

If you don't set it, by default, the behaviour will be to return `null` if an error occurs.

So I think I'll keep the `json.php` file. I might rewrite it though to use the new flag by default.
