### ISSUE TITLE
Warning: ldap_bind() expects at most 3 parameters, 4 given

### ISSUE THREAD

**Issue by localheinz** [thecodingmachine/safe#187]
When using `thecodingmachine/safe:1.0.2` on PHP 7.3.11, we have observed the following warning:

> Warning: ldap_bind() expects at most 3 parameters, 4 given

When looking at

* https://github.com/php/php-src/blob/php-7.3.11/ext/ldap/ldap.c#L1142-L1194
* https://github.com/php/php-src/blob/php-7.4.1/ext/ldap/ldap.c#L1117-L1169

it's not apparent that `ldap_bind()` accepts 4 arguments.

In contrast, the wrapping function `Safe\ldap_bind()` accepts and invokes `ldap_bind()` with 4 arguments :

* https://github.com/thecodingmachine/safe/blob/v1.0.2/generated/ldap.php#L90-L97

The documentation, from which the code is generated, states that `ldap_bind()` accepts 4 arguments:

* https://www.php.net/manual/en/function.ldap-bind.php

Perhaps there is something wrong with the documentation?

**Comment by OskarStark** [comment]
I couldn't find any occurence in the PHP source code where `ldap_bind()` accepts 4 arguments, but the docs say it can:
https://github.com/php/doc-en/blob/060a8e23b015eec8692a921dcc6f21f669928a51/reference/ldap/functions/ldap-bind.xml#L16

cc @nikic , as [php/doc-en](https://github.com/php/doc-en) is only a mirror, how can we fix that?

**Comment by localheinz** [comment]
Also see https://github.com/php/doc-en/pull/20.

**Comment by Kharhamel** [comment]
this issue is solved in v1.0.3

**Comment by OskarStark** [comment]
Thank you!
