### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by davidsneighbour** [thecodingmachine/safe#190]
I have code that accesses the $_SESSION global. Thats bad ;) The error message says (sample):

```
 83     In method "Booka\Page\Tracking::hasLogrocket", you should not use the $_SESSION superglobal. You should instead rely on your framework that provides you with a "request" object (for instance a PSR-7 RequestInterface or a Symfony Request). More info: http://bit.ly/nosuperglobals              
```

Symfony Request is not working for $_SESSION globals. [filter_input_array()](https://www.php.net/manual/en/function.filter-input-array.php) is not filtering $_SESSION. 

What is the expected proper way to access `$_SESSION` variables?

**Comment by moufmouf** [comment]
Hey @davidsneighbour ,

I believe this issue belongs to a completely different package.

Namely: https://github.com/thecodingmachine/phpstan-strict-rules

Could you reopen it in this package?
