### ISSUE TITLE
date function is missing

### ISSUE THREAD

**Issue by iquito** [thecodingmachine/safe#218]
The `date` function can return false (if a non-numeric value is used for `$timestamp`). I suspect this was not included in this library because static analyzers used to not report this - but with psalm 3.11.4 this changed and it is now reported.

I suspect so far it is only reported if psalm cannot clearly determine that a numeric value was used for `$timestamp`, but with legacy applications that can easily happen, and having a definite `string` return type would avoid the ambiguity. Therefore having a safe `date` function would be nice addition to this library!

**Comment by Kharhamel** [comment]
Ok, i will look into this

**Comment by Kharhamel** [comment]
This was added in the v1.3.2 release.
I am sorry it took so long, I didn't have a lot of time for safe recently.

**Comment by iquito** [comment]
No problem, thanks for adding it!
