### ISSUE TITLE
Add @throw tag in phpdoc

### ISSUE THREAD

**Issue by VincentLanglet** [thecodingmachine/safe#219]
Throwing exception instead of returning false is a nice idea... only if you catch these exception.

There is a phpstan package (https://github.com/pepakriz/phpstan-exception-rules) to check that every exception are correctly handle. In order to work, it need that every exception thrown in a method are described in a `@throws` tag.

I think it could be a great idea to update the phpdoc of all the wrapper to add the `@throws` tag.

Edit: Maybe this is only missing for \DateTime and \DateTimeImmutable.

**Comment by Kharhamel** [comment]
If it is only on DateTime and DateTimeImmutable, this should be quick to fix. I will do it shortly

**Comment by Kharhamel** [comment]
#222

**Comment by Kharhamel** [comment]
I will release this shortly
