### ISSUE TITLE
Errors when running on PHP8

### ISSUE THREAD

**Issue by WouterSioen** [thecodingmachine/safe#225]
When running the project (throuh the infection package) on PHP8, I get this error:

```
PHP Warning:  "resource" is not a supported builtin type and will be interp  
reted as a class name. Write "\Safe\resource" or import the class with "use  
" to suppress this warning
```

It looks like the `resource` typehint in the `generated/sockets.php` file in the
`socket_wsaprotocol_info_export` method is not supported in PHP8 and should
thus be removed to make this library and infection compatible with PHP8.

**Comment by WouterSioen** [comment]
You can see the difference between PHP7 and PHP8 here: https://3v4l.org/JVrNp

**Comment by Kharhamel** [comment]
This  project is not designed to run on php 8. There are too much functions which will have their signature changed or which will natively throw exceptions on error. We are actually working on making this behavior as common as possible in php 8 by submiting pr to the source code.
Ideally you shouldn't need Safe in php 8 in the first place.

**Comment by ondrejmirtes** [comment]
The problem is that the "resource" typehint doesn't work even on PHP 7, it just thinks it's an object of that type: https://3v4l.org/GLq3g

**Comment by ondrejmirtes** [comment]
"Argument 1 passed to socket_wsaprotocol_info_export() must be an instance of resource, resource given"

**Comment by fezfez** [comment]
PR updated :)
