### ISSUE TITLE
pack and unpack missing

### ISSUE THREAD

**Issue by fezfez** [thecodingmachine/safe#243]
Hi,

for both method (pack and unpack), phpdoc never say it can return false but JetBrains/phpstorm-stubs say it can.
After checking in php src i found it can be return false see : https://github.com/php/php-src/blob/master/ext/standard/tests/strings/bug61038.phpt

[pack definition in phpstorm-stubs](https://github.com/JetBrains/phpstorm-stubs/blob/5b7def27af1f88c009f137b4c4a38bb4732a3713/standard/standard_7.php#L162) 
[unpack definition in phpstorm-stubs](https://github.com/JetBrains/phpstorm-stubs/blob/5b7def27af1f88c009f137b4c4a38bb4732a3713/standard/standard_7.php#L176)

**Comment by fezfez** [comment]
fixed in phpdoc via https://bugs.php.net/bug.php?id=80187

**Comment by Kharhamel** [comment]
There have been some big changes in the documentation recently that could create a lot of issue in safe if i merge now. I have to design a fix first before i can do other fixes, sorry

**Comment by Kharhamel** [comment]
pack and unpack were added in v1.3.0
