### ISSUE TITLE
Cannot redeclare Safe\array_combine()

### ISSUE THREAD

**Issue by j3j5** [thecodingmachine/safe#253]
Hi there, congrats on the project, I just discovered it and I think is great.

Now, I've tried to add it to one of my libraries and now when I run phpstan (with our without the rule) I get the following error:
```
PHP Fatal error:  Cannot redeclare Safe\array_combine() (previously declared in /home/user/project/vendor/thecodingmachine/safe/generated/array.php:20) in /home/user/project/vendor/thecodingmachine/safe/generated/array.php on line 20

Fatal error: Cannot redeclare Safe\array_combine() (previously declared in /home/user/project/vendor/thecodingmachine/safe/generated/array.php:20) in /home/user/project/vendor/thecodingmachine/safe/generated/array.php on line 20

In array.php line 20:
                                                                                                                                                              
  Cannot redeclare Safe\array_combine() (previously declared in /home/user/project/vendor/thecodingmachine/safe/generated/array.php:20)  
                                                                                                                                                              
```

The file obviously don't have the function declared twice and I'm completely lost as for where it could be coming from. Any ideas? I'm on 1.3.3.

Thanks!

**Comment by Kharhamel** [comment]
I don't know sorry. Do you still have the issue if you remove the library and re install it with composer?

**Comment by j3j5** [comment]
Steps to reproduce:
- Clone [this repo](https://github.com/thenextweb/passgenerator)
- Run `composer install`
- Run `./vendor/bin/phpstan analyse`

It should be reproducible on your machine, I'm using PHP 7.4.11 just in case it has anything to do.

**Comment by j3j5** [comment]
I've been digging a bit further, the issue is only with the `array_` functions but I can't find why phpstan thinks they've been previously declared. If I remove [the line from composer.json](https://github.com/thecodingmachine/safe/blob/master/composer.json#L21) that includes the `array.php` file and dump the autoloader classes again, phpstan runs just fine. 

It is a very strange issue.

FWIW, installing the library on another project and using it doesn't seem to throw the error, so everything points to an error on `phpstan` and how it loads the autoloader, but I have no idea where else to look.

**Comment by nepda** [comment]
Do you have any updates on this?

**Comment by MJTheOne** [comment]
This is still an issue. Just ran into it myself

**Comment by nepda** [comment]
It seems like the `function_exists` call is dropped, and the issue is a thing again.

**Comment by tpetry** [comment]
It's happening on `2.1.2` for me too.

**Comment by webard** [comment]
In combination with phpstan or rector, the error still occurs (v2.1.2).

**Comment by dbrekelmans** [comment]
As pointed out in https://github.com/thecodingmachine/safe/issues/253#issuecomment-726762555, this issue seems to be more related to phpstan than to Safe. As far as I can tell, we only declare `Safe\array_combine` once (see: https://github.com/thecodingmachine/safe/search?q=array_combine%28).

Does this still occur if you disable the phpstan safe extension? If so, it's most likely a bug in https://github.com/thecodingmachine/phpstan-safe-rule

**Comment by dbrekelmans** [comment]
I've re-opened this issue per https://github.com/thecodingmachine/phpstan-safe-rule/issues/29#issuecomment-1060366739

**Comment by dongm2ez** [comment]
I have some problem. But function is array_flip. 

`PHP Fatal error:  Cannot redeclare Safe\array_flip()`,

thecodingmachine/safe: v2.1.2
nunomaduro/larastan: 1.0.3

**Comment by j3j5** [comment]
Left a comment on the [larastan repo](https://github.com/nunomaduro/larastan/issues/741#issuecomment-1063067587), I'm pretty sure the issue is on there. The different errors come from different versions of `thecodingmachine/safe`, it used to be only one `array.php` file but now there are 2 with different functions.

**Comment by j3j5** [comment]
It turns out I was wrong and the issue was *not* on larastan but on the Safe library.

I left [a comment](https://github.com/nunomaduro/larastan/issues/741#issuecomment-1068673078) on the larastan issue commenting my findings but long story short, the issue comes from using `array` as a param or return type on PHPDocs. Since all functions are defined within the `Safe` namespace and `Safe\array` points to a file following PSR4 specs, PHPStan tries to load the class `Safe\array` by loading the file `array.php`, which was already loaded and then causes the _Cannot redeclare_ errors.

Changing the type on the PHPDocs to `\array` (making the global namespace specific) fixes the error, but it needs to be changed on all Safe functions that deal or return an array.

**Comment by szepeviktor** [comment]
@Kharhamel Please consider storing class files and function files in separate directories.

**Comment by asbiin** [comment]
@j3j5 This one is still not fixed, maybe you could reopen the issue?
Thank you for your work! I hope you'll find a proper fix soon ...

**Comment by asbiin** [comment]
I also have the exact same error with `array_flip`:
```php
      Cannot redeclare Safe\array_flip() (previously declared in               
     vendor/thecodingmachine/safe/deprecated/array.php:27)                                                               
                                                                                
       at vendor/thecodingmachine/safe/deprecated/array.php:27                  
          23▕  * @throws ArrayException                                         
          24▕  * @deprecated The Safe version of this function is no longer     
     needed in PHP 8.0+                                                         
          25▕  *                                                                
          26▕  */                                                               
       ➜  27▕ function array_flip(array $array): array                          
          28▕ {                                                                 
          29▕     error_clear_last();                                           
          30▕     $result = \array_flip($array);                                
          31▕     if ($result === null) {                                       
```

**Comment by j3j5** [comment]
@asbiin You are right, it isn't fixed, or at least, the fix isn't merged yet. There was a MR which we thought fixed the error but it was reverted since it actually didn't fix it (#333 if I'm not mistaken). Anyway, there's an open MR right now (#350) which should fix it for good. 
Also, if #348 gets into an actual MR and it gets merged will also fix this. I don't know why this issue was closed in the first place.

**Comment by Kharhamel** [comment]
I created a new pre release tag to test @j3j5 new fix.

**Comment by Kharhamel** [comment]
@j3j5 did you test the new tag? Did it solve your issue?

**Comment by j3j5** [comment]
Yes, so far the error is gone from my packages that include both, larastan and safe. Also, I've been running the alpha on [a personal project](https://gitlab.com/j3j5/twitter-bots/-/blob/main/composer.lock#L9528) and I didn't find any issue so far.

**Comment by Kharhamel** [comment]
Very well, I think I will do an official release soon.
