### ISSUE TITLE
Function preg_match not working properly

### ISSUE THREAD

**Issue by WillyReyno** [thecodingmachine/safe#26]
Method preg_match doesn't seem to be working properly after installing Safe.

I made a regex to split spotify URL and retrieve the id. Here is my code which is working when I remove  Safe's use function : 
```
public function getTrackIdFromUrl(string $url): ?string
    {
        $spotifyRegex = "/https?:\/\/(?:embed\.|open\.)(?:spotify\.com\/)(?:track\/|\?uri=spotify:track:)((\w|-){22})/";
        preg_match($spotifyRegex, $url, $matches);
        return $matches[1] ?? null;
    }
```
For the url `https://open.spotify.com/track/0nCqpKBrvDchO1BIvt7DTR?si=iLUKDfkLSy-IpnLA7qImnw` the return of $matches[1] should be `0YCRJcAXQ3NSfKN1x1IXK3`.
With Safe, $matches returns null.

Thank you for the awesome lib :)

**Comment by mallardduck** [comment]
Give this a shot here:

```
public function getTrackIdFromUrl(string $url): ?string
    {
        $spotifyRegex = "/https?:\/\/(?:embed\.|open\.)(?:spotify\.com\/)(?:track\/|\?uri=spotify:track:)((\w|-){22})/";
        $matches = [];
        preg_match($spotifyRegex, $url, $matches);
        return $matches[1] ?? null;
    }
```

**Comment by WillyReyno** [comment]
Well, that was simple. Thank you! 

However I don't know if the package should change the behavior of the original method (even though it was a bit magic)?

**Comment by mallardduck** [comment]
Sure thing, glad I could help!

I haven't tested it myself - yet - however I think it may be a behavior that's unavoidable when shimming this type of function. I'll test it for real and then report back.

**Comment by mallardduck** [comment]
So after a bit of testing I found out that you're correct in that this change in behavior could be avoided. I'm not sure how that would be done since I'm not familiar with the generation of the shims - but changing the behavior here should be avoidable for sure.

Essentially just turning the last `elseif` into the `else` used would fix it.

**Comment by moufmouf** [comment]
Hoooo I see... Thanks @WillyReyno and @mallardduck  for pointing this out.

Just reproduced the error in a unit test. The issue arises with all functions that have optional "by reference" arguments.

I'm trying to implement @mallardduck fix in the code generator right now.

**Comment by moufmouf** [comment]
....aaaaand it's fixed!

https://github.com/thecodingmachine/safe/commit/03998c2fcfe93de64d33bfad9465521d239551f3

:)

Thanks to all of you!
