### ISSUE TITLE
Missing getcwd function?

### ISSUE THREAD

**Issue by kasperg** [thecodingmachine/safe#29]
Thanks a bunch for sharing safe. It helps me up my PHPStan level without writing to much tedious code.

One question: Is the [`getcwd()` function](http://php.net/manual/en/function.getcwd.php) missing?

I tried looking into this and the documentation seems as if it would be detected as falsy and as far as I can tell neither module nor function is explicitly declared as ignored.

> Returns the current working directory on success, or FALSE on failure. 

I tried running the generation but cloning the documentation fails because of timeouts 😕 .

**Comment by moufmouf** [comment]
Yeah... I'm having the same problem right now. The documentation SVN seems to be down since approximately one hour. Hopefully, it will be fixed soon.

**Comment by moufmouf** [comment]
Regarding `getcwd`, you are perfectly right, it should be detected.

Detection is done in `DocPage::detectFalsyFunction`: https://github.com/thecodingmachine/safe/blob/726b9993e0a80fd125a2ce4ca777ae6bdacd03cb/generator/src/DocPage.php#L26-L48

It is really heuristic as the doc can be written in a lot of different ways.

I'll fix this for `getcwd`

**Comment by kasperg** [comment]
I took a stab at this myself. We can continue the discussion in the PR.
