### ISSUE TITLE
Which version of php/doc-en was used?

### ISSUE THREAD

**Issue by fox91** [thecodingmachine/safe#291]
I am trying to regenerate the latest version `1.3.3` and I have noticed a big problem: I don't know which version of [php/doc-en](https://github.com/php/doc-en) was used.
The problem with [php/doc-en](https://github.com/php/doc-en) is that no tags are used, it is constantly evolving and correctly documents the current version of PHP but not the previous ones (for example I wanted to try to fix the #289 problem but I cannot regenerate version `1.3.3`).
I therefore recommend using git submodules to keep track of which specific commit is used for each version of Safe.

Is there any trace somewhere of which [php/doc-en](https://github.com/php/doc-en) commit was used for each specific tag (at least the latest `1.3.3`) of Safe in order to reproduce it correctly?

**Comment by dbrekelmans** [comment]
Hi @fox91, the generator simply clones the git repo, so it's always using the latest master to generate the files. We currently don't track which commit from the docs is used for which release of Safe. If you have have ideas on how to accomplish this, feel free to open a PR and I will take a look at it!

**Comment by fox91** [comment]
Hi @dbrekelmans, I've opened #292.
It's based on tag v1.3.3, for `php/doc-en` I chose a commit created on the same date as yours that doesn't necessarily match the one you actually used but generates the same output.

**Comment by dbrekelmans** [comment]
This was resolved in https://github.com/thecodingmachine/safe/pull/292

**Comment by fox91** [comment]
Hi @dbrekelmans,
in my opinion it would be a good idea to apply the same thing also for the master branch.
I don't think it makes much sense to only do this for a branch that probably won't get updates anymore.
What do you think? Can I open a PR about it?

**Comment by dbrekelmans** [comment]
It was important for this branch, because it's for an older php version. `master` only supports the most current php8, so we actually do want the latest phpdoc. There are different options for supporting multiple php version, one of which is outlined in https://github.com/thecodingmachine/safe/issues/317. But nobody is actively working on it at the moment.
