### ISSUE TITLE
Wrong Type in Method swoole_async_write

### ISSUE THREAD

**Issue by BITWINGS-DE** [thecodingmachine/safe#293]
Message:
Warning: "integer" will be interpreted as a class name. Did you mean "int"? Write "\Safe\integer" or import the class with "use" to suppress this warning in /.../vendor/thecodingmachine/safe/generated/swoole.php on line 17

i think this is only in php 8

**Comment by dbrekelmans** [comment]
Hi @BITWINGS-DE, which version of Safe are you using and which version of PHP?

Looking at line 17 in https://github.com/thecodingmachine/safe/blob/v1.3.3/generated/swoole.php, I don't see how this error could occur. Could you give some more context? Which function are you calling and how are you calling it?

**Comment by BITWINGS-DE** [comment]
ok, I have seen that the culprit is another module that is still loading an outdated version.

Issue can be closed.


silverstripe/silverstripe-webauthn-authenticator (wrong version inplemented) > web-auth/webauthn-lib > web-auth/cose-lib > thecodingmachine/safe

crazy nested ;)
