### ISSUE TITLE
ArgumentCountError in fputcsv()

### ISSUE THREAD

**Issue by snapshotpl** [thecodingmachine/safe#310]
Version: 2.0.0-alpha.3
PHP: 8.0

```
fputcsv() expects at most 5 arguments, 6 given
```

Documentation say:

```
8.1.0 | The optional eol parameter has been added.
```
by https://www.php.net/manual/en/function.fputcsv.php

**Comment by Jean85** [comment]
@dbrekelmans we can surely pin to that, but wouldn't this make the library compatible with 8.0.* only? How would you deal with SemVer? And what about downstream libs, how could they pin against this lib?

**Comment by dbrekelmans** [comment]
Hi @Jean85, yes that would be the case. It would require us to make a new minor for each php version. It's definitely not ideal.

I think the ideal situation (in my opinion) would be to keep track of some sort of delta like phpstan and psalm do (example: https://github.com/phpstan/phpstan-src/blob/master/resources/functionMap_php80delta.php).
In fact, I would love it if Safe would take phpstan as the base source of truth and only fall back to the php docs if phpstan is missing knowledge.

This would be a big refactor though, which I personally don't have the time for at the moment, but if anyone is willing to try then I definitely want to encourage them!

**Comment by Jean85** [comment]
@dbrekelmans I would like to give it a try, but I'm not sure that I understood your suggestion... How would this work? Do you want to generate the functions conditionally using PHPStan as a source of truth? Also, PHPStan seems to be listing a lot more functions that we would want... We would still need to use the doc as a listing, and then use PHPStan as a primary source for signature.

In the meantime, I've wrote #316 as a (temporary?) fix for this issue.

**Comment by dbrekelmans** [comment]
@Jean85 Thanks for the PR, I will take a look!

> We would still need to use the doc as a listing, and then use PHPStan as a primary source for signature.

Yes that is correct. I was too quick to think we might not need the docs since phpstan knows the return type, but of course we still need to find out from the docs if this is a case of "return false on error"

I have outlined my thoughts in a new issue: https://github.com/thecodingmachine/safe/issues/317, so we don't pollute this one :).
If it's not clear or you have any questions, feel free to ask in that issue!
