### ISSUE TITLE
JSON example does not appear to be correct

### ISSUE THREAD

**Issue by iltar** [thecodingmachine/safe#35]
The example in the readme is not correct, it doesn't take NULL as valid json. While technically it doesn't really happen often, it's still a legit use-case:
```php
$foobar = json_decode($content);
if ($foobar === null) {
    throw new FileLoadingException('foobar.json does not contain valid JSON: '.json_last_error());
}
```
As shown here, `null === json_decode(json_encode(null));`
https://3v4l.org/Oq7sE

**Comment by moufmouf** [comment]
You are 100% correct.

@davide_b88 also declared the issue on Twitter: https://twitter.com/davide_b88/status/1040503898438610944

Hopefully, Safe implementation is correct, but I definitely need to fix the README.

https://github.com/thecodingmachine/safe/blob/master/lib/special_cases.php#L27-L34
