### ISSUE TITLE
Too few arguments to function Safe\Exceptions\CurlException::createFromPhpError()

### ISSUE THREAD

**Issue by drobek94** [thecodingmachine/safe#365]
In ```Safe\Exceptions\CurlException``` function ```createFromPhpError``` expect parametr ```\CurlHandle $ch```. This function is called from ```generated/curl.php``` without the param.

Ends with error:
```Too few arguments to function Safe\Exceptions\CurlException::createFromPhpError()```

Thank you very much.

**Comment by Kharhamel** [comment]
This is deployed with v2.2.2
