### ISSUE TITLE
Automate Rector file creation

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/safe#38]
Rector can be used to massively apply Safe functions through a complete codebase.

Writing the config file can be long (there are >900 functions to replace)

We should see if it is possible to generate a rector config file or a rector extension that does this.

**Comment by moufmouf** [comment]
@TomasVotruba @rectorphp

**Comment by TomasVotruba** [comment]
Great idea :+1: 

I think the same way you generate function, just generate the `rector.yml` file.

Then it coul be run like:

```
vendor/bin/rector process src --config vendor/thecodingmachine/safe/migrate-rector.yml
```

And with autoimports:

```
vendor/bin/rector process src --config vendor/thecodingmachine/safe/migrate-rector.yml --with-style
```

**Comment by moufmouf** [comment]
Done in #40
