### ISSUE TITLE
BC break in patch release 2.2.3

### ISSUE THREAD

**Issue by davidyell** [thecodingmachine/safe#392]
In my work project we implement the `json_decode` method and it seems there is a method signature change between `2.2.2` and `2.2.3` which breaks our codebase.

I am curious why the method params would be changed outside of a major release in-line with Semver. https://semver.org/

If this is an intentional change, then I would recommend some documentation around it, as stipulating a Composer constraint of `^2.0` and implementing the class with a pre `2.2.3` release, when using `composer update` the code will break.

https://getcomposer.org/doc/articles/versions.md#caret-version-range-

The intention of this constraint is that updates should be safe.

**Comment by colinodell** [comment]
There's some further discussion of this in https://github.com/thecodingmachine/safe/pull/376#issuecomment-1205475926

**Comment by davidyell** [comment]
Thanks @colinodell 

I will close this as duplicate of that discussion
