### ISSUE TITLE
PHP 8.2 deprecation: Return type of Safe\DateTimeImmutable::createFromMutable($dateTime): Safe\DateTimeImmutable

### ISSUE THREAD

**Issue by staabm** [thecodingmachine/safe#413]
on PHP 8.2 we see deprecation errors like

> Deprecated: Return type of Safe\DateTimeImmutable::createFromMutable($dateTime): Safe\DateTimeImmutable should either be compatible with DateTimeImmutable::createFromMutable(DateTime $object): static, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/gharlan/workspace/redaxo/redaxo/src/addons/rexstan/vendor/thecodingmachine/safe/lib/DateTimeImmutable.php on line 239

**Comment by jakubvojacek** [comment]
There already is a PR solving this. 

https://github.com/thecodingmachine/safe/pull/406
