### ISSUE TITLE
Is this package still actively maintained?

### ISSUE THREAD

**Issue by aidan-casey** [thecodingmachine/safe#439]
Hey there! First and foremost, I want to express my appreciation for all the hard work that has already been poured into this package. It is definitely helpful to me.

Upon reviewing the repository, it seems that forward progress has slowed down over the past year. Between open issues, pull requests, commit history, and the absence of certain functions (e.g., `ob_get_clean`), it looks like there might be some necessary work to bring this package up to speed.

With that in mind, I wanted to inquire about the current direction and maintenance status of the package. Is there a roadmap for future updates or releases? Are there any specific plans to address the open issues and pull requests?

I would love to see this package updated and continue to be helpful to the ecosystem. I'm not sure if it is helpful, but I would be more than willing to contribute my time toward maintenance efforts if another maintainer is needed to see that happen.

**Comment by shish** [comment]
Looks like the answer is "no", but I want this package to exist and be maintained - so I've [forked it](https://github.com/shish/safe), merged many of the outstanding pull requests (and fixed all the merge conflicts...), added more of my own fixes on top, made it php8.4 compatible, and released as `shish/safe` (and marked as `replaces: thecodingmachine/safe` - so if you require `shish/safe` and your internal dependencies use `thecodingmachine/safe`, it _should_ all Just Work...)

**Comment by staabm** [comment]
we have new maintainers for this package

**Comment by nepda** [comment]
Nice, thank you so much :heart:

Is there a place where we can find more information about the maintainers change and roadmap?

**Comment by staabm** [comment]
we discuss a new release here: https://github.com/thecodingmachine/safe/issues/499
