### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ATouhou** [thecodingmachine/safe#44]
Hello.
Could you do a benchmark of perfomance impact with and without using this :-) 
Thank you

**Comment by moufmouf** [comment]
That was at some point in my TODO list, but I must admit I forgot a bit the performance part.

:+1: I'll keep this issue open until I find some time to benchmark the lib.

**Comment by ATouhou** [comment]
Thanks :-)! looking forward :D

**Comment by mickaelandrieu** [comment]
is a Blackfire profile from your test suite can help?

**Comment by moufmouf** [comment]
.... and it is finally done.

Bottom line: adding Safe to your projects takes ~700µs for the autoloading part, on each request. This is quite low considering there are 1000+ functions loaded.

More details: https://github.com/thecodingmachine/safe/tree/master/performance

See #51 

Don't hesitate to reopen an issue if you have more specific questions.
