### ISSUE TITLE
Are you looking for maintainers here?

### ISSUE THREAD

**Issue by OskarStark** [thecodingmachine/safe#452]
It looks like there is not much activity here, so I would offer my help to maintain this repository.

Cheers, Oskar

cc @mvhirsch @igst @silasjoisten @localheinz @staabm

**Comment by silasjoisten** [comment]
I would too.

**Comment by shish** [comment]
FWIW I have a maintained fork (with nearly all of the PR's here merged, flagged as a drop-in replacement so you only need to update dependencies for the top-level composer.json) at https://github.com/shish/safe

**Comment by moufmouf** [comment]
Hey all!

Sorry, @Kharhamel and I have had some hectic schedule. I'm working full time on WorkAdventure and obviously don't have enough time to maintain the project appropriately.

So, YES! we are looking for maintainers.

I'll do my best to put Safe in a correct state for PHP 8.4, but Safe definitely needs some love. @shish I'll probably backport the changes in your fork. Do you want to be added as a maintainer? (@OskarStark, @silasjoisten I would be happy to add you too, shall I do that?)

**Comment by OskarStark** [comment]
Yes please add both of us (Silas and I are working together)

**Comment by moufmouf** [comment]
@OskarStark @silasjoisten   Done!
What would be the good way of doing things starting from here? Backporting all @shish changes and then starting merging submitted PRs that are not already part of @shish work?

**Comment by silasjoisten** [comment]
Sounds good to me!

**Comment by shish** [comment]
Yeah I'm happy to be added as a maintainer and avoid fragmentation :)

**Comment by OskarStark** [comment]
@staabm, what about you?

**Comment by staabm** [comment]
sure, why not

**Comment by moufmouf** [comment]
Cool!
@shish @staabm @OskarStark @silasjoisten You have all be added to this repo and the PHPStan extension.

Super happy to have you guys as maintainers. I should have done that way before!

I think the best thing to do for me is to step aside and let you guys merge your respective PRs and tag releases accordingly. You are all experienced maintainers so I won't get in the way! :heart:

**Comment by OskarStark** [comment]
Thanks for the trust and being open 🖖 community will thank you 🙏

**Comment by danepowell** [comment]
When you backport the changes, I'd appreciate if you please don't drop support for PHP 8.1 until it's officially EOL next year 😄 

https://github.com/thecodingmachine/safe/pull/441#issuecomment-2499226690
