### ISSUE TITLE
Why `shuffle`?

### ISSUE THREAD

**Issue by mvhirsch** [thecodingmachine/safe#454]
I'm currently refactoring a large code base. I'm using rector and this wonderful library to make it safer :-) 

I stumbled upon `shuffle` and wonder: why? In which circumstances does it return false? 

https://github.com/thecodingmachine/safe/blob/3a6e43b4be3d3d65b272c2660300a50658ce168b/generated/array.php#L52-L56

According to [php documentation](https://www.php.net/manual/en/function.shuffle.php#refsect1-function.shuffle-returnvalues) this never happens.

**Comment by shish** [comment]
In PHP7, shuffle would return `false` if it was passed something other than an array as input. This library hasn't been updated to be compatible with PHP8, where type hints take care of that category of issue (FYI I'm maintaining a PHP8-compatible fork of Safe at https://github.com/shish/safe )

**Comment by mvhirsch** [comment]
> In PHP7, shuffle would return false if it was passed something other than an array as input. 

That's not even mentioned in the offical php docs, is it?

**Comment by shish** [comment]
That is correct, the docs are lacking in many ways, but you can check the source code

https://github.com/php/php-src/blob/PHP-7.2/ext/standard/array.c#L3041

https://github.com/php/php-src/blob/PHP-8.4/ext/standard/array.c#L3312

**Comment by mvhirsch** [comment]
Source is undeniable. Thank you very much.
