### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/safe#5]
Scanning of lib.php by PHPStorm alone takes several minutes.
We should also check performance for PHP.

TODO: try to split the file in several smaller files?

**Comment by moufmouf** [comment]
Some measures:

When everything function is in one single big file:

- nb functions: 1426
- nb lines: 46514
- file size: 1.3M
- time to index in PHPStorm: 3m42s

**Comment by moufmouf** [comment]
Results after splitting functions in 128 files:

- nb functions: 128
- nb lines: 48449
- files size (total): 1.5M
- average file size: 12k
- time to index in PHPStorm: *3s* (!!!)

**Comment by MaXal** [comment]
The difference shouldn't be so enormous! Is it possible to attach `lib.php`? We (PhpStorm team) would glad to investigate what is going on.

**Comment by moufmouf** [comment]
Hey @MaXal 

With pleasure. File is here:

[lib.zip](https://github.com/thecodingmachine/safe/files/2357447/lib.zip)

It takes about 3 minutes to index with latest version of PHPStorm (2018.2)

And I'm not having this problem if file is splitted in 128 smaller files (I'm in the process of commiting those, so they will be in the repository by tomorrow).

**Comment by MaXal** [comment]
Thanks a lot! Reproduced: https://youtrack.jetbrains.com/issue/WI-43453

**Comment by moufmouf** [comment]
Cool. Happy to help if I can.
I'll close this issue since this is now in your hands :)

**Comment by neuro159** [comment]
CC: 2M file with 2853 non-absolute Exceptions namespace reference eg @throws Exceptions\ApacheException -> was a full file scan for use for each ref.
Note: such syntax is DISCOURAGED. Workaround -> always use absolute NS ref in such cases!
Anyway, fixed ns total ref resolve local 5 min->100ms on indexing (or typing)

**Comment by neuro159** [comment]
You guys might want to change all those  
@throws Exceptions\ApacheException 
to  
@throws \Exceptions\ApacheException

**Comment by moufmouf** [comment]
Woot! That was fast. Thanks a lot @neuro159 !
And I'll sure fix the relative reference!
