### ISSUE TITLE
call_user_func_array can return false

### ISSUE THREAD

**Issue by jyggen** [thecodingmachine/safe#73]
`call_user_func_array` returns the return value of the callback, or `false` on error, which means that `false` could very well be a valid and expected.

https://secure.php.net/call_user_func_array

**Comment by moufmouf** [comment]
Damn it! How could I let that slip through?
There is no proper way to handle errors in `call_user_func_array` and `call_user_func`. I cannot possibly deal with protected methods in a proper way.
I'll simply remove the functions altogether from Safe.

Thanks a lot for opening this issue.
