### ISSUE TITLE
strtotime error

### ISSUE THREAD

**Issue by jakubvojacek** [thecodingmachine/safe#75]
Hello,

believe there is an issue with default value of `$now` in `strtotime` method.

These two are not equal while they should be, I think.
```
\Safe\strtotime('+ 1 hour') !== strtotime('+ 1 hour')
```

The default value should be `"time()"` instead of `null`

Am I right or is it expected behavior?

Thank you

**Comment by moufmouf** [comment]
:+1:

Thanks for the issue. I'll look into it ASAP.
Related to #83 and #85

**Comment by moufmouf** [comment]
Closed in #85 
Actually, there were way more functions impacted. I think I caught them all :)
