### ISSUE TITLE
Strpos is missing

### ISSUE THREAD

**Issue by simPod** [thecodingmachine/safe#78]
http://php.net/manual/en/function.strpos.php

States:

> Returns FALSE if the needle was not found.

IMO it should be included in Safe

**Comment by simPod** [comment]
I'm not saying it's error. But the behaviour is twisted. Exception != Error

**Comment by moufmouf** [comment]
Completely agree with @bolmstedt .
strpos is often used to find if a string is part of another string. You expect it to return false.
You should not use exceptions for control-flow, only to handle hard errors. Hence, it's logical to me that `strpos` returns false if the needle was not found.

**Comment by Chemaclass** [comment]
I almost submit a new issue with this exact same question. I understand this now and it makes sense. Thanks, @bolmstedt!
