### ISSUE TITLE
array_search should not be part of Safe

### ISSUE THREAD

**Issue by bolmstedt** [thecodingmachine/safe#80]
`array_search` says:
> Returns the key for needle if it is found in the array, FALSE otherwise.

It is not an error not finding something you search for, therefore it seems to be outside of Safe's scope.

**Comment by simPod** [comment]
For me: I would rather expect `null` or thrown exception but definitelly not `FALSE`.

🤔

**Comment by moufmouf** [comment]
o_O You are perfectly right!
I definitely need to fix this!
