### ISSUE TITLE
add date creation methods?

### ISSUE THREAD

**Issue by bendavies** [thecodingmachine/safe#82]
these can return false:
http://php.net/manual/en/function.date-create-from-format.php
http://php.net/manual/en/function.date-create-immutable-from-format.php

there are probably others? WDYT?

**Comment by rieschl** [comment]
...and what about  the `DateTime` and `DateTimeImmutable` classes? They "convert" invalid date strings which is even worse than `false` and just log it in `DateTime::getLastErrors`
Or is this package restricted to functions?

**Comment by moufmouf** [comment]
@bendavies You are perfectly right.
The fact is I generate the Safe functions from the PHP doc (there are too many functions to do that manually).
date_create_from_format is an alias of DateTime::createFromFormat and is not documented as the other functions. My code generator for Safe doesn't know yet how to handle the aliases (or the classes).

It is definitely on the TODO for Safe v1 though. Any help is welcome by the way :)
Also, this is directly related to #7

**Comment by Kharhamel** [comment]
#138

**Comment by Kharhamel** [comment]
we now have custom datetime classes in safe in 1.0.0-beta1. Don't hesitate to test them
