### ISSUE TITLE
strtotime needs a special case

### ISSUE THREAD

**Issue by bendavies** [thecodingmachine/safe#83]
Hi there!
Thanks for the great library!
I think I've found a bug when integrating safe into my project.

Because of this:
https://3v4l.org/HL9Xn
`strtotime('+1 day')` is not equivalent to `\Safe\strtotime('+1 day')`, so looks to need some special handling, to not pass null as the 2nd param if the caller didn't specifically pass null, or enforce int for the 2nd param, or pass `time()` manually if null.

Thanks

**Comment by moufmouf** [comment]
True! The default value for the second parameter in the PHP doc is "time()" (which of course is not a "valid" default value from a PHP standpoint). It gets replaced by null and that causes the issue.

Looking at the documentation, the `touch` function might also be impacted.

**Comment by moufmouf** [comment]
Closed in #85
